# Generated by Django 6.0.5 on 2026-08-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0012_recoveryslot_notification_basis'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoveryslot',
            name='use_ai_decision',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
